//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenalyCalculationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookId { get; set; }
        public string bookName { get; set; }
        public Nullable<System.DateTime> checkedOutDate { get; set; }
    }
}
